# Adding UUIDs to Reservations

In [1]:
import pandas as pd
import uuid

In [2]:
data = pd.concat([pd.read_csv('../../data/source/H1.csv'),
                  pd.read_csv('../../data/source/H2.csv')],
                 axis = 0)
data

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0.0,...,No Deposit,NULL,NULL,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0.0,...,No Deposit,NULL,NULL,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0.0,...,No Deposit,NULL,NULL,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0.0,...,No Deposit,304,NULL,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0.0,...,No Deposit,240,NULL,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79325,0,23,2017,August,35,30,2,5,2,0.0,...,No Deposit,394,NULL,0,Transient,96.14,0,0,Check-Out,2017-09-06
79326,0,102,2017,August,35,31,2,5,3,0.0,...,No Deposit,9,NULL,0,Transient,225.43,0,2,Check-Out,2017-09-07
79327,0,34,2017,August,35,31,2,5,2,0.0,...,No Deposit,9,NULL,0,Transient,157.71,0,4,Check-Out,2017-09-07
79328,0,109,2017,August,35,31,2,5,2,0.0,...,No Deposit,89,NULL,0,Transient,104.40,0,0,Check-Out,2017-09-07
79329,0,205,2017,August,35,29,2,7,2,0.0,...,No Deposit,9,NULL,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [3]:
# Generate UUIDs for each row in the dataframe
data['UUID'] = [uuid.uuid4() for _ in range(len(data))]
data

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate,UUID
0,0,342,2015,July,27,1,0,0,2,0.0,...,NULL,NULL,0,Transient,0.00,0,0,Check-Out,2015-07-01,8c8f9f34-fb93-4004-a605-465266a85a53
1,0,737,2015,July,27,1,0,0,2,0.0,...,NULL,NULL,0,Transient,0.00,0,0,Check-Out,2015-07-01,139441b3-d4c1-4c47-bf0d-584dc919470f
2,0,7,2015,July,27,1,0,1,1,0.0,...,NULL,NULL,0,Transient,75.00,0,0,Check-Out,2015-07-02,c3d6793d-187e-4d1f-9304-0154cbdec51c
3,0,13,2015,July,27,1,0,1,1,0.0,...,304,NULL,0,Transient,75.00,0,0,Check-Out,2015-07-02,cfb040e4-d31b-44bb-87b6-43826b94ea41
4,0,14,2015,July,27,1,0,2,2,0.0,...,240,NULL,0,Transient,98.00,0,1,Check-Out,2015-07-03,a761cfc1-27e6-4879-ab34-d6c2f13ece3c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79325,0,23,2017,August,35,30,2,5,2,0.0,...,394,NULL,0,Transient,96.14,0,0,Check-Out,2017-09-06,f7ace865-8a8a-49bf-85fe-6eec7a9b0f73
79326,0,102,2017,August,35,31,2,5,3,0.0,...,9,NULL,0,Transient,225.43,0,2,Check-Out,2017-09-07,20e4d2fa-1011-4046-9130-e45e8605a1a9
79327,0,34,2017,August,35,31,2,5,2,0.0,...,9,NULL,0,Transient,157.71,0,4,Check-Out,2017-09-07,44bc1961-7048-4817-ad00-904ddedd16bf
79328,0,109,2017,August,35,31,2,5,2,0.0,...,89,NULL,0,Transient,104.40,0,0,Check-Out,2017-09-07,d3078365-c2a8-473b-b996-bb4fada7f5e4
79329,0,205,2017,August,35,29,2,7,2,0.0,...,9,NULL,0,Transient,151.20,0,2,Check-Out,2017-09-07,f437841f-3c45-4d78-89bf-41e09d801a59

In [4]:
data['UUID'] = data['UUID'].astype(str)
data['UUID']

0        8c8f9f34-fb93-4004-a605-465266a85a53
1        139441b3-d4c1-4c47-bf0d-584dc919470f
2        c3d6793d-187e-4d1f-9304-0154cbdec51c
3        cfb040e4-d31b-44bb-87b6-43826b94ea41
4        a761cfc1-27e6-4879-ab34-d6c2f13ece3c
                         ...
79325    f7ace865-8a8a-49bf-85fe-6eec7a9b0f73
79326    20e4d2fa-1011-4046-9130-e45e8605a1a9
79327    44bc1961-7048-4817-ad00-904ddedd16bf
79328    d3078365-c2a8-473b-b996-bb4fada7f5e4
79329    f437841f-3c45-4d78-89bf-41e09d801a59
Name: UUID, Length: 119390, dtype: object

In [5]:
data = data.set_index('UUID')
data

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
UUID,,,,,,,,,,,,,,,,,,,,,
8c8f9f34-fb93-4004-a605-465266a85a53,0,342,2015,July,27,1,0,0,2,0.0,...,No Deposit,NULL,NULL,0,Transient,0.00,0,0,Check-Out,2015-07-01
139441b3-d4c1-4c47-bf0d-584dc919470f,0,737,2015,July,27,1,0,0,2,0.0,...,No Deposit,NULL,NULL,0,Transient,0.00,0,0,Check-Out,2015-07-01
c3d6793d-187e-4d1f-9304-0154cbdec51c,0,7,2015,July,27,1,0,1,1,0.0,...,No Deposit,NULL,NULL,0,Transient,75.00,0,0,Check-Out,2015-07-02
cfb040e4-d31b-44bb-87b6-43826b94ea41,0,13,2015,July,27,1,0,1,1,0.0,...,No Deposit,304,NULL,0,Transient,75.00,0,0,Check-Out,2015-07-02
a761cfc1-27e6-4879-ab34-d6c2f13ece3c,0,14,2015,July,27,1,0,2,2,0.0,...,No Deposit,240,NULL,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
f7ace865-8a8a-49bf-85fe-6eec7a9b0f73,0,23,2017,August,35,30,2,5,2,0.0,...,No Deposit,394,NULL,0,Transient,96.14,0,0,Check-Out,2017-09-06
20e4d2fa-1011-4046-9130-e45e8605a1a9,0,102,2017,August,35,31,2,5,3,0.0,...,No Deposit,9,NULL,0,Transient,225.43,0,2,Check-Out,2017-09-07
44bc1961-7048-4817-ad00-904ddedd16bf,0,34,2017,August,35,31,2,5,2,0.0,...,No Deposit,9,NULL,0,Transient,157.71,0,4,Check-Out,2017-09-07
d3078365-c2a8-473b-b996-bb4fada7f5e4,0,109,2017,August,35,31,2,5,2,0.0,...,No Deposit,89,NULL,0,Transient,104.40,0,0,Check-Out,2017-09-07
f437841f-3c45-4d78-89bf-41e09d801a59,0,205,2017,August,35,29,2,7,2,0.0,...,No Deposit,9,NULL,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [6]:
data.to_feather('../../data/source/full_data.feather', compression = 'zstd')